name: Update vercel.json (Daily)

on:
  # 日本時間で毎日 8:00 に実行 (UTCでは 23:00)
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-vercel-and-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Run update-vercel script
        run: yarn update_vercel

      - name: Create Pull Request to staging
        id: pr-to-staging
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'update-vercel-redirects-${{ github.run_number }}'
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          title: 'chore: update vercel.json (auto-generated)'
          commit-message: 'chore: update vercel.json based on daily schedule'
          base: 'staging'
          delete-branch: true

      - name: Enable auto-merge on staging PR
        if: steps.pr-to-staging.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.pr-to-staging.outputs.pull-request-number }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge staging changes into main locally
        run: |
          # 最新の staging を取得して main にマージ
          git checkout main
          git pull origin main
          git merge origin/staging

      - name: Create Pull Request (staging -> main)
        id: sync-staging-into-main
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-staging-into-main
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          commit-message: 'chore: sync staging into main'
          title: 'Sync staging into main'
          base: 'main'

      - name: Enable auto-merge on main PR
        if: steps.sync-staging-into-main.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.sync-staging-into-main.outputs.pull-request-number }}
          token: ${{ secrets.GITHUB_TOKEN }}
