name: Update vercel.json (Daily)

on:
  # 日本時間で毎日8:00に実行 (UTCでは 23:00)
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-vercel-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Run update-vercel script
        run: yarn update_vercel

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'update-vercel-redirects-${{ github.run_number }}'
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          title: 'chore: update vercel.json (auto-generated)'
          commit-message: 'chore: update vercel.json based on daily schedule'
          base: 'staging'
          delete-branch: true
      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure git
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
  
      - name: Merge staging into main branch
        if: steps.cpr.outputs.pull-request-number != ''
        run: |
          git pull origin staging
          # ターゲットブランチ(開発ブランチ)をチェックアウト
          git checkout main
          git pull origin main
          # staging の変更をマージ
          git merge --no-commit staging || true
  
      - name: Create Pull Request
        id: sync-staging-into-main
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-stating-into-main
          author: GitHub Action <action@github.com>
          committer: GitHub Action <action@github.com>
          commit-message: "chore: sync staging into main"
          title: "Sync staging into main"
          base: "main"
          path: "."
      - name: Enable auto-merge
        if: steps.cpr.outputs.pull-request-number != ''
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ steps.sync-staging-into-main.outputs.pull-request-number }}
          token: ${{ secrets.GITHUB_TOKEN }}